version: "3.5"

services:
  db_gazprom:
    container_name: gazprom_test
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:16.1-alpine
